apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000 #
    hostPort: 30000
    protocol: TCP
  - containerPort: 32000 #
    hostPort: 32000
    protocol: TCP
  - containerPort: 30115 #
    hostPort: 30115
    protocol: TCP
- role: worker