apiVersion: v1
kind: Service
metadata:
  labels:
    component: webserver
    release: airflow
    tier: airflow
  name: airflow-webserver
  namespace: airflow
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    component: webserver
    release: airflow
    tier: airflow
  type: NodePort
